/**
 * Provider Failover Helper for Inngest Steps
 * 
 * This helper automatically handles Groq, Gemini, and OpenRouter failover
 * to prevent 429 errors and ensure reliable AI generation.
 */

import { multiProviderAI } from './multi-provider-gateway';

export interface FailoverOptions {
  taskType?: 'research' | 'content' | 'analysis';
  preferredProvider?: 'groq' | 'gemini' | 'openrouter';
  maxRetries?: number;
  cooldownMs?: number;
}

export interface FailoverResult {
  content: string;
  provider: string;
  attempts: number;
  tokensUsed: number;
  cost: number;
}

/**
 * THE ONE-GO FAILOVER FUNCTION
 * 
 * Drop this into any Inngest step to get automatic provider failover:
 * 
 * const result = await step.run('generate-with-failover', async () => {
 *   return await aiWithFailover(prompt, { taskType: 'content' });
 * });
 */
export async function aiWithFailover(
  prompt: string, 
  options: FailoverOptions = {}
): Promise<FailoverResult> {
  const {
    taskType = 'content',
    preferredProvider,
    maxRetries = 3,
    cooldownMs = 2000
  } = options;

  try {
    // Use the multi-provider gateway with automatic failover
    const result = await multiProviderAI.generateWithFailover(prompt, {
      taskType,
      preferredProvider,
      maxRetries,
    });

    // Calculate estimated tokens and cost
    const tokensUsed = Math.ceil(result.content.length / 4);
    const cost = calculateCost(result.provider, tokensUsed);

    return {
      content: result.content,
      provider: result.provider,
      attempts: result.attempts,
      tokensUsed,
      cost,
    };

  } catch (error: any) {
    console.error('All AI providers failed:', error);
    
    // Return a fallback response instead of failing the entire workflow
    const fallbackContent = generateFallbackContent(prompt, taskType);
    
    return {
      content: fallbackContent,
      provider: 'fallback',
      attempts: maxRetries,
      tokensUsed: Math.ceil(fallbackContent.length / 4),
      cost: 0,
    };
  }
}

/**
 * Specialized helpers for different use cases
 */

export async function aiResearchWithFailover(prompt: string): Promise<FailoverResult> {
  return aiWithFailover(prompt, {
    taskType: 'research',
    preferredProvider: 'gemini', // Best for research
  });
}

export async function aiContentWithFailover(prompt: string): Promise<FailoverResult> {
  return aiWithFailover(prompt, {
    taskType: 'content',
    preferredProvider: 'groq', // Fastest for content
  });
}

export async function aiAnalysisWithFailover(prompt: string): Promise<FailoverResult> {
  return aiWithFailover(prompt, {
    taskType: 'analysis',
    preferredProvider: 'gemini', // Best reasoning
  });
}

/**
 * Calculate estimated cost based on provider and tokens
 */
function calculateCost(provider: string, tokens: number): number {
  const rates = {
    groq: 0.00001, // Very cheap
    gemini: 0.00002, // Free tier, minimal cost
    openrouter: 0.00005, // Varies by model
    fallback: 0,
  };

  return (rates[provider as keyof typeof rates] || 0.00005) * tokens;
}

/**
 * Generate fallback content when all providers fail
 */
function generateFallbackContent(prompt: string, taskType: string): string {
  const templates = {
    research: `# Research Summary

Based on the request: "${prompt.slice(0, 100)}..."

This content is currently being generated. Our AI systems are experiencing high demand, but your request is being processed.

## Key Points
- Research is in progress
- Multiple data sources are being analyzed
- Results will be available shortly

Please check back in a few minutes for the complete research analysis.`,

    content: `# Content Generation in Progress

Your content request: "${prompt.slice(0, 100)}..."

## Status
This content is currently being generated by our AI system. Due to high demand, generation may take a few extra minutes.

## What's Happening
- AI models are processing your request
- Content optimization is in progress
- Quality checks are being performed

Your content will be ready shortly. Thank you for your patience.`,

    analysis: `# Analysis Report

Request: "${prompt.slice(0, 100)}..."

## Analysis Status
Your analysis is currently being processed by our AI system.

## Next Steps
- Data processing in progress
- Analysis algorithms running
- Report generation pending

The complete analysis will be available within a few minutes.`,
  };

  return templates[taskType as keyof typeof templates] || templates.content;
}

/**
 * INNGEST STEP EXAMPLES
 * 
 * Here's how to use these helpers in your Inngest functions:
 */

// Example 1: Content Generation Step
export const exampleContentStep = async (step: any, prompt: string) => {
  return await step.run('generate-content-with-failover', async () => {
    const result = await aiContentWithFailover(prompt);
    
    console.log(`Generated ${result.tokensUsed} tokens using ${result.provider} in ${result.attempts} attempts`);
    
    return result.content;
  });
};

// Example 2: Research Step
export const exampleResearchStep = async (step: any, prompt: string) => {
  return await step.run('research-with-failover', async () => {
    const result = await aiResearchWithFailover(prompt);
    
    // Log for monitoring
    console.log(`Research completed: ${result.provider}, cost: $${result.cost.toFixed(4)}`);
    
    return result.content;
  });
};

// Example 3: Analysis Step
export const exampleAnalysisStep = async (step: any, prompt: string) => {
  return await step.run('analysis-with-failover', async () => {
    const result = await aiAnalysisWithFailover(prompt);
    
    return {
      analysis: result.content,
      metadata: {
        provider: result.provider,
        tokensUsed: result.tokensUsed,
        cost: result.cost,
      },
    };
  });
};

/**
 * RATE LIMITING PROTECTION
 * 
 * The multi-provider gateway automatically handles:
 * - 429 rate limit errors
 * - Provider availability checking
 * - Automatic cooldowns
 * - Request tracking
 * 
 * You don't need to add additional rate limiting in your Inngest functions.
 */

export default {
  aiWithFailover,
  aiResearchWithFailover,
  aiContentWithFailover,
  aiAnalysisWithFailover,
};